### PR TITLE
Capitalize Fortran Package Manager as proper noun

### PR DESCRIPTION
**Pull request by awvwgk**
- rebuild all po-files, they are not really whitespace stable unfortunately

Preview deployed to https://awvwgk.github.io/fpm-docs/

### CODE REVIEW

**Comment by aslozada** [comment]
If the term "Fortran Package Manager" is a proper name, should it be translated?

**Comment by awvwgk** [comment]
Good question. I would still translate it.

**Review by milancurcic — APPROVED** [review]
Looks good, thanks.

I don't know how these .po files work. What's a good reference?

**Comment by awvwgk** [comment]
> I don't know how these .po files work. What's a good reference?

I collected a few references in https://github.com/fortran-lang/fpm-docs/issues/5

**Comment by awvwgk** [comment]
Will go ahead and merge.

**Comment by aslozada** [comment]
Some sections that have already been translated are back in English.

cn:

de:

es:

**Comment by awvwgk** [comment]
This would be related to the change in #27 and here, which reworded most text on the main page. You can find those mismatched translations in the po file with a `fuzzy` attribute:

https://github.com/fortran-lang/fpm-docs/blob/99a8dddd917f75ed461cb3cc933f8e87c118d3df/locale/es/LC_MESSAGES/index.po#L45-L54

Text that was reworded in a way that it doesn't match anymore for the translation will be commented out rather than removed:

https://github.com/fortran-lang/fpm-docs/blob/99a8dddd917f75ed461cb3cc933f8e87c118d3df/locale/es/LC_MESSAGES/index.po#L137-L144

**Comment by awvwgk** [comment]
I'll do a cleanup of the translation for the minor changes. I'll leave the other changes in as fuzzy, those require some review by you, even if the translations will most likely match alright. Feel free to push changes to #32.

**Comment by aslozada** [comment]
Conflicts with my fork. I'm a little confused.
"Open a pull request to fetch upstream and review changes or resolve conflicts."

**Comment by awvwgk** [comment]
Best to not work on the `main` branch, you can fix this up with:
```
git checkout main
git fetch git@github.com:fortran-lang/fpm-docs
git reset --hard FETCH_HEAD
git push --force git@github.com:aslozada/fpm-docs
```

**Comment by aslozada** [comment]
Sebastian @awvwgk: Thanks very much. The ```upstream (fetch)``` was in awvwgk/fpm-docs

**Pull request merged**
