### PR TITLE
Add translation files for Portuguese

### PR DESCRIPTION
**Pull request by awvwgk**
- sphinx language identifiers for Portuguese:
  https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language
  - `pt` – Portuguese
  - `pt_BR` – Brazilian Portuguese
  - `pt_PT` – European Portuguese
- sphinx-book-theme supports only `pt` as language identifier:
  https://github.com/executablebooks/sphinx-book-theme/tree/master/src/sphinx_book_theme/assets/translations

### CODE REVIEW

**Comment by 14NGiestas** [comment]
It's fine, but I can only help with the pt_BR, so the official translation to Portuguese will be Brazilian flavored ~the right and widely spoken anyway xD~.

**Review by 14NGiestas — APPROVED** [review]

**Comment by awvwgk** [comment]
I raised an issue at https://github.com/executablebooks/sphinx-book-theme/issues/600 about missing support for language variants.

**Comment by awvwgk** [comment]
My suggestion is to start with `pt` as language identifier for now, when we arrive at the point at which we want both an European and Brazilian flavored Portuguese translation, we can still move towards `pt_PT` and `pt_BR` as language identifiers.

**Comment by awvwgk** [comment]
Now available at https://hosted.weblate.org/projects/fortran-lang/fpm/pt/.

**Pull request merged**
