### PR TITLE
Add page about fpm logo

### LINKED ISSUE #49: Use fpm logo
@1984logo Do you have a source for the logo we can work with (svg, ...), I would make a start and incorporate it in the fpm documentation as favicon and sidebar logo.

Also, I plan to include a page on the logo itself and how it should be used in the design section.

From https://github.com/fortran-lang/fpm/discussions/380#discussioncomment-2079206

### PR DESCRIPTION
**Pull request by awvwgk**
Adds a design page to introduce the fpm logo (discussed in https://github.com/fortran-lang/fpm/discussions/380 and developed by @1984logo). The logo is provided as

- monochromatic version in Fortran-lang purple
- colorful version using the fpm color palette
- light monochromatic version for dark backgrounds
- light outline version for dark backgrounds

Closes #49 

image

### CODE REVIEW

**Comment by 1984logo** [comment]
@awvwgk I just noticed your PR. Good job!

**Comment by 1984logo** [comment]
@awvwgk I noticed that the svg in this commit is different from the latest version.

You can find below the latest version in black and colored version

```
<svg id="fpm" width="563" height="683" viewBox="0 0 563 683" fill="none" xmlns="http://www.w3.org/2000/svg">
<path id="_1" d="M313,0C207.51-1.33,88,75.25,64,207.94H259.7a29.61,29.61,0,0,1,28.95-24.17Z" fill="black"/>
<path id="_2" d="M342.52,0H557.73A4.28,4.28,0,0,1,562,4.82L536.08,207.93H340.35c1.54-13.26-8-24-21.25-24.17Z" fill="black"/>
<path id="_3" d="M255.64,237.05H58.56L31.9,445H253.3l23.56-183.75C263.58,261.06,254.1,250.3,255.64,237.05Z" fill="black"/>
<path id="_4" d="M530.63,237.05H336.42a29.6,29.6,0,0,1-28.94,24.17L284.06,445H498.48a6.41,6.41,0,0,0,6.36-5.6Z" fill="black"/>
<path id="_5" d="M26.08,474.08h221.4L221.54,676.41a6.41,6.41,0,0,1-6.36,5.59H4.27A4.28,4.28,0,0,1,0,677.19Z" fill="black"/>
</svg>
```

```
<svg id="fpm" width="563" height="683" viewBox="0 0 563 683" fill="none" xmlns="http://www.w3.org/2000/svg">
<path id="_1" d="M313,0C207.51-1.33,88,75.25,64,207.94H259.7a29.61,29.61,0,0,1,28.95-24.17Z" fill="#9953AD"/>
<path id="_2" d="M342.52,0H557.73A4.28,4.28,0,0,1,562,4.82L536.08,207.93H340.35c1.54-13.26-8-24-21.25-24.17Z" fill="#A34E9C"/>
<path id="_3" d="M255.64,237.05H58.56L31.9,445H253.3l23.56-183.75C263.58,261.06,254.1,250.3,255.64,237.05Z" fill="#6853AD"/>
<path id="_4" d="M530.63,237.05H336.42a29.6,29.6,0,0,1-28.94,24.17L284.06,445H498.48a6.41,6.41,0,0,0,6.36-5.6Z" fill="#734F96"/>
<path id="_5" d="M26.08,474.08h221.4L221.54,676.41a6.41,6.41,0,0,1-6.36,5.59H4.27A4.28,4.28,0,0,1,0,677.19Z" fill="#4E52A3"/>
</svg>
```

**Comment by awvwgk** [comment]
> I noticed that the svg in this commit is different from the latest version.

I still have to update them with yours, hopefully will find some time for this by end of the week.

**Review by milancurcic — APPROVED** [review]
Pending any outstanding SVG update, this can be merged, no? It looks good as is.

**Comment by awvwgk** [comment]
> will find some time for this by end of the week.

I was very optimistic with my time schedule back then but forgot about this patch while writing my thesis.

I'll have a look again.

**Comment by awvwgk** [comment]
Updated the logo with the svgs provided by @1984logo.

**Pull request merged**
