### PR TITLE
docs: add installation instructions for fpm

### PR DESCRIPTION
**Pull request by gnikit**
Linked to https://github.com/fortran-lang/fpm/pull/778. Moved installation instructions to fpm-docs from README.

## Summary

Included also spack in the installation document.

Also, rearranged the grid in the main page
to have a offer installation prior to entering the
Tutorial section.

The How-To section is now empty, not sure if it's needed.

### CODE REVIEW

**Comment by gnikit** [comment]
as @LKedward mentioned in https://github.com/fortran-lang/fpm/pull/785#issuecomment-1291580067 `macos-latest` seems to break the CI so I have fixed it to `11`.

**Review by milancurcic — APPROVED** [review]

**Comment by gnikit** [comment]
> Do we have a preview feature here? I'm not too familiar with the syntax to parse it in my head, but the content seems okay.

No unfortunately not. Let me try and add the action now.

**Review by LKedward — APPROVED** [review]

**Comment by gnikit** [comment]
@milancurcic I added some preview workflows they **should work** (fingers crossed) but I couldn't properly test them on my local fork, sphinx refused to build so if they don't work I will revert the commit and put them in another PR.

**Comment by gnikit** [comment]
#preview

**Review by awvwgk — APPROVED** [review]
Thanks, looks good to me.

**Pull request merged**
